"""add ai analyzed timestamp

Revision ID: 23278f8d7c2e
Revises: b7ace5f65698
Create Date: 2026-09-06 13:02:17.272652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23278f8d7c2e'
down_revision: Union[str, Sequence[str], None] = 'b7ace5f65698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
