"""add diabetes ml analysis fields

Revision ID: 9993a9e09859
Revises: 23278f8d7c2e
Create Date: 2026-09-09 19:54:25.133824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9993a9e09859'
down_revision: Union[str, Sequence[str], None] = '23278f8d7c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('ml_diabetes_risk_score', sa.Float(), nullable=True))
    op.add_column('medical_records', sa.Column('ml_diabetes_prediction', sa.String(length=50), nullable=True))
    op.add_column('medical_records', sa.Column('ml_diabetes_model', sa.String(length=100), nullable=True))
    op.add_column('medical_records', sa.Column('ml_diabetes_feature_coverage', sa.Float(), nullable=True))
    op.add_column('medical_records', sa.Column('ml_diabetes_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'ml_diabetes_analyzed_at')
    op.drop_column('medical_records', 'ml_diabetes_feature_coverage')
    op.drop_column('medical_records', 'ml_diabetes_model')
    op.drop_column('medical_records', 'ml_diabetes_prediction')
    op.drop_column('medical_records', 'ml_diabetes_risk_score')
    # ### end Alembic commands ###
