"""add ai analyzed timestamp

Revision ID: b7ace5f65698
Revises: 94e30965c1ac
Create Date: 2026-09-06 12:55:51.890602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ace5f65698'
down_revision: Union[str, Sequence[str], None] = '94e30965c1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('ai_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'ai_analyzed_at')
    # ### end Alembic commands ###
